### ISSUE TITLE
Code not compatible with Python 3.8 upwards

### ISSUE THREAD

**Issue by alexkleinwaechter** [BeamNG/blender-forest-exporter#1]
Hi,
in Blender 3.0 the exporter throws an error.
It seems that:

time.clock() 

is not supported anymore.
I just commented out the lines with time.clock() because they are only used to measure the processing time.

**Comment by thomatoes50** [comment]
fixed in [0.2.1](https://github.com/BeamNG/blender-forest-exporter/releases/tag/v0.2.1)
